config/routes.rb
Rails.application.routes.draw do
  mount GovukPublishingComponents::Engine, at: "/component-guide" if Rails.env.development?

  # Healthchecks
  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  resource :search, only: %i[show]
  resource :feedbacks, only: %i[create]
  resource :settings, only: %i[show update]

  get "/how-to-rate", to: "pages#how_to_rate", as: :how_to_rate

  root "searches#show"
end

app/models/feedback.rb
require "google/cloud/bigquery"

class Feedback
  include ActiveModel::Model
  include ActiveModel::Validations

  validates :suggested_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), allow_blank: true, message: "must be a valid URL" }

  attr_accessor :search_query, :result_ratings, :suggested_url, :comments, :user_id, :discovery_engine_attribution_token

  def result_ratings_attributes=(attributes)
    @result_ratings = attributes.map do |_, v|
      ResultRating.new(
        content_id: v["content_id"],
        link: v["link"],
        position: v["position"].to_i,
        rating: v["rating"].presence&.to_i, # nil rating is legitimate, don't convert to zero
      )
    end
  end

  def save
    return false unless valid?

    dataset = Google::Cloud::Bigquery.new.dataset(Rails.configuration.bigquery_dataset)
    table = dataset.table(Rails.configuration.bigquery_table)

    data = to_bigquery_row
    table.insert(data)
    Rails.logger.info "Feedback submitted: #{data.inspect}"
  end

  def to_bigquery_row
    {
      query_id: SecureRandom.uuid,
      anonymised_user_id: user_id,
      timestamp: Time.zone.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%3NZ"),
      search_query:,
      result_ratings: result_ratings.map(&:to_bigquery_data),
      suggested_url:,
      comments:,
      discovery_engine_attribution_token:,
    }
  end
end

app/models/result.rb
class Result
  include ActiveModel::Model

  attr_accessor :title, :description, :link, :content_id, :document_type, :public_timestamp, :parts

  def parts?
    parts.any?
  end
end

app/models/result_rating.rb
class ResultRating
  RATING_OPTIONS = {
    3 => "Perfect",
    2 => "Good",
    1 => "OK",
    0 => "Bad",
  }.freeze

  include ActiveModel::Model

  attr_accessor :content_id, :link, :position, :rating

  def self.rating_options
    RATING_OPTIONS
  end

  def id = content_id

  def to_bigquery_data
    {
      content_id:,
      url:,
      position: position + 1, # have it 1-indexed in BigQuery
      rating:,
    }
  end

  def url
    if link.start_with?("/")
      Plek.new.website_root + link
    else
      link
    end
  end
end

app/models/search.rb
require "gds_api/search"

class Search
  include ActiveModel::Model

  attr_accessor :query, :count

  def show_results?
    query.present?
  end

  def results
    response["results"].map do |result|
      timestamp = Time.zone.parse(result["public_timestamp"])

      Result.new(
        title: result["title"],
        description: result["description_with_highlighting"],
        link: result["link"],
        content_id: result["content_id"],
        document_type: result["content_store_document_type"],
        public_timestamp: timestamp,
        parts: (result["parts"] || []).map { |part| part["title"] },
      )
    end
  end

  def displayed_count
    response["results"].size
  end

  def total_count
    response["total"]
  end

  def discovery_engine_attribution_token
    response["discovery_engine_attribution_token"]
  end

private

  def response
    @response ||= search_service.search(
      q: query,
      count:,
    ).to_hash
  end

  def search_service
    @search_service ||= ::GdsApi::SearchApiV2.new(Plek.find("search-api-v2"))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  if ENV["BASIC_AUTH_USERNAME"] && ENV["BASIC_AUTH_PASSWORD"]
    http_basic_authenticate_with(
      name: ENV.fetch("BASIC_AUTH_USERNAME"),
      password: ENV.fetch("BASIC_AUTH_PASSWORD"),
    )
  end

private

  def user_id
    cookies[:user_id] ||= SecureRandom.uuid
  end

  def show_more_results?
    ActiveModel::Type::Boolean.new.cast(cookies[:show_more_results])
  end
  helper_method :show_more_results?

  def show_metadata?
    ActiveModel::Type::Boolean.new.cast(cookies[:show_metadata])
  end
  helper_method :show_metadata?
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      flash[:success] = "Thank you for your feedback - it will help improve the new GOV.UK search."
      redirect_to search_path
    else
      @search = Search.new(query: @feedback.search_query)
      render "searches/show"
    end
  end

private

  def feedback_params
    params.require(:feedback).permit(
      :search_query, :suggested_url, :comments, :discovery_engine_attribution_token, result_ratings_attributes: {}
    ).merge(user_id:)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def how_to_rate; end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.new(query_params)
    @feedback = Feedback.new(
      search_query: @search.query,
      result_ratings: @search.results.map.with_index { |r, i| ResultRating.new(content_id: r.content_id, link: r.link, position: i) },
      discovery_engine_attribution_token: @search.discovery_engine_attribution_token,
    )
  end

private

  def query_params
    params.permit(:query).merge(count: show_more_results? ? 10 : 5)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  SETTINGS_KEYS = %i[show_more_results show_metadata].freeze

  def show
    @settings = SETTINGS_KEYS.index_with do |key|
      ActiveModel::Type::Boolean.new.cast(cookies[key])
    end
  end

  def update
    SETTINGS_KEYS.each do |key|
      cookies.permanent[key] = ActiveModel::Type::Boolean.new.cast(settings_params[key])
    end

    flash[:success] = "Your settings have been updated."
    redirect_to settings_path
  end

private

  def settings_params
    params.permit(*SETTINGS_KEYS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def govuk_link_to(text, link)
    full_url = if link.start_with?("http")
                 link
               else
                 Plek.new.website_root + link
               end

    link_to text, full_url, class: "govuk-link"
  end
end

app/views/layouts/application.html.erb
<%= render "govuk_publishing_components/components/layout_for_admin", {
  environment: Rails.configuration.govuk_environment,
  product_name: "Search Evaluation",
  browser_title: yield(:title).presence || "Try the new search engine",
} do %>
  <%= render "govuk_publishing_components/components/skip_link" %>
  <%= render "govuk_publishing_components/components/layout_header", {
    environment: Rails.configuration.govuk_environment,
    product_name: "Try the new search engine",
    navigation_items: [
      {
        text: "Advanced settings",
        href: settings_path,
        active: current_page?(settings_path)
      }
    ]
  } %>
  <div class="govuk-width-container">
    <main class="govuk-main-wrapper">
      <% if flash[:success] %>
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-full">
          <%= render "govuk_publishing_components/components/success_alert", {
            message: flash[:success]
          } %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </div>
  <%= render "govuk_publishing_components/components/layout_footer" %>
  <%= javascript_importmap_tags %>
<% end %>

app/views/pages/how_to_rate.html.erb
<%= render "govuk_publishing_components/components/back_link", {
  href: search_path
} %>

<h1 class="govuk-heading-l">How to rate search results</h1>

<h4 class="govuk-heading-s">Perfect</h4>
<p class="govuk-body">
  Based on your search term, the result is completely relevant. More than one result can be perfect.
</p>
<h4 class="govuk-heading-s">Good</h4>
<p class="govuk-body">
  The result is clearly reasonable. You are not surprised that the search term brought back this result.
</p>
<h4 class="govuk-heading-s">OK</h4>
<p class="govuk-body">
  You can see why we returned the result, but it isn't very helpful. For example, a search for
  “Find my local council” may return a page about how to pay a parking charge to your local council. You can see why it appeared
  (because it includes a reference to local councils) but it isn’t directly relevant for your search term.
</p>
<h4 class="govuk-heading-s">Bad</h4>
<p class="govuk-body">
  The result has no apparent relationship to your search term.
</p>

app/views/searches/_result.html.erb
<li class="search-results__result">
  <%= form.hidden_field :content_id %>
  <%= form.hidden_field :link %>
  <%= form.hidden_field :position %>
  <div class="search-results__details">
    <h2 class="search-results__title">
      <%= govuk_link_to result.title, result.link %>
    </h2>
    <p class="search-results__url"><%= result.link %></p>
    <p class="search-results__description"><%= result.description %></p>
    <% if result.parts? %>
      <p class="search-results__parts">
        <strong>Parts:</strong>
        <%= result.parts.join(", ") %>
      </p>
    <% end %>
    <% if show_metadata? %>
      <div class="search-results__metadata">
        <span class="search-results__metadata-item search-results__metadata-item--content-type">
          <%= result.document_type %>
        </span>
        <span class="search-results__metadata-item">
          Public timestamp: <%= result.public_timestamp.strftime("%e %b %Y") %> (<%= time_ago_in_words result.public_timestamp %> ago)
        </span>
        <span class="search-results__metadata-item">
          Content ID: <%= result.content_id %>
        </span>
      </div>
    <% end %>
  </div>
  <fieldset class="search-results__ranking">
    <legend class="search-results__ranking-legend">
      How relevant is this result?
    </legend>
    <% ResultRating.rating_options.each do |value, label| %>
      <label class="search-results__ranking-option search-results__ranking-option--<%= value %>">
        <%= form.label :rating, label, value: %>
        <%= form.radio_button :rating, value %>
      </label>
    <% end %>
  </fieldset>
</li>

app/views/searches/show.html.erb
<div class="query-container govuk-grid-row">
  <%= form_with url: search_path, method: :get do |form| %>
    <div class="govuk-grid-column-two-thirds">
      <%= render "govuk_publishing_components/components/search", {
        inline_label: false,
        label_size: "m",
        label_text: "Search GOV.UK using the new search engine",
        value: @search.query,
        name: "query",
      } %>
    </div>
  <% end %>
</div>

<% if @feedback.errors.any? %>
  <%= render "govuk_publishing_components/components/error_summary", {
    id: "error-summary",
    title: "There was a problem with your feedback",
    description: "You need to correct these errors before you can submit your feedback.",
    items: @feedback.errors.details.map { |field, error|
      {
        text: @feedback.errors.full_messages_for(field).first,
        href: "#feedback_#{field}",
      }
    }
  } %>
<% end %>

<% if @search.show_results? %>
  <div class="results-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-one-half">
        <h2 class="govuk-heading-s">
          Showing top <%= pluralize(@search.displayed_count, "result") %>
          (out of <%= number_with_delimiter(@search.total_count) %>)
        </h2>
      </div>
      <div class="results-container__rate govuk-grid-column-one-half">
        <%= link_to "Learn how to rate results", how_to_rate_path, class: "govuk-link" %>
      </div>
    </div>
    <%= form_with model: @feedback do |form| %>
      <%= form.hidden_field :search_query %>
      <%= form.hidden_field :discovery_engine_attribution_token %>
      <div class="govuk-grid-row search-results">
        <div class="govuk-grid-column-full">
          <ul class="search-results__list">
            <%= form.fields_for :result_ratings do |ff| %>
              <%= render partial: "searches/result", locals: { form: ff, result: @search.results[ff.object.position] } %>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="govuk-grid-row search-feedback">
        <div class="govuk-grid-column-two-thirds search-feedback__fields">
          <%= render "govuk_publishing_components/components/details", {
            title: "Is the best possible result not included?",
            open: @feedback.errors.include?(:suggested_url),
          } do %>
            <div class="govuk-form-group <%= 'govuk-form-group--error' if @feedback.errors.include?(:suggested_url) %>">
              <%= form.label :suggested_url, "URL for the best possible result", class: "govuk-label" %>
              <div class="govuk-hint">Enter the full URL of a page on GOV.UK (or an external link) that you think is a better result for your query than any of the results shown.</div>
              <% if @feedback.errors.include?(:suggested_url) %>
                <p id="national-insurance-number-error" class="govuk-error-message">
                  <span class="govuk-visually-hidden">Error:</span> <%= @feedback.errors.full_messages_for(:suggested_url).join(", ") %>
                </p>
              <% end %>
              <%= form.text_field :suggested_url, class: "govuk-input" %>
            </div>
          <% end %>

          <%= render "govuk_publishing_components/components/details", {
            title: "Do you have any other comments about these results?",
          } do %>
            <%= form.label :comments, "Your comments about these results", class: "govuk-label" %>
            <%= form.text_area :comments, class: "govuk-textarea" %>
          <% end %>
        </div>
        <div class="govuk-grid-column-one-third search-feedback__submit">
          <%= render "govuk_publishing_components/components/button", {
            text: "Submit feedback",
            type: "submit",
          } %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/settings/show.html.erb
<h1 class="govuk-heading-l">Advanced settings</h1>
<p class="govuk-body">
  These settings are intended for use within the Search Improvement team and you probably don't need
  to change them if you just want to give feedback on search results from the perspective of a
  regular user.
</p>
<div class="govuk-inset-text">
  Settings are stored in your cookies and will be reset if you do not have cookies enabled or clear
  your browser data.
</div>


<%= form_with url: settings_path, method: :put do |form| %>
  <div class="govuk-form-group">
    <fieldset class="govuk-fieldset" aria-describedby="waste-hint">
      <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
        <h2 class="govuk-fieldset__heading">
          Which advanced settings do you want to enable?
        </h2>
      </legend>
      <div class="govuk-checkboxes" data-module="govuk-checkboxes">
        <div class="govuk-checkboxes__item">
          <%= form.check_box :show_more_results, class: "govuk-checkboxes__input", checked: @settings[:show_more_results] %>
          <%= form.label :show_more_results, "Show more results", class: "govuk-label govuk-checkboxes__label" %>
          <div id="more-results-hint" class="govuk-hint govuk-checkboxes__hint">
            Show 10 results per page instead of 5
          </div>
        </div>
        <div class="govuk-checkboxes__item">
          <%= form.check_box :show_metadata, class: "govuk-checkboxes__input", checked: @settings[:show_metadata] %>
          <%= form.label :show_metadata, "Show metadata for results", class: "govuk-label govuk-checkboxes__label" %>
          <div id="metadata-hint" class="govuk-hint govuk-checkboxes__hint">
            Shows additional information like document type or public timestamp for each result
          </div>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="govuk-form-group">
    <%= form.submit "Save settings", class: "govuk-button" %>
  </div>
<% end %>